# SPDX-FileCopyrightText: Copyright (c) 2022-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: copyrights
'on':
  push:
  pull_request:
jobs:
  copyrights:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: yegor256/copyrights-action@0.0.12
        with:
          globs: >-
            **/LICENSE.txt
            **/Makefile
            **/*.sh
            **/*.yml
            **/*.yaml
            **/*.java
            **/*.xml
            **/*.hs
            **/*.hi
            **/*.cpp
            **/*.hpp
            **/*.h
            **/*.c
            **/*.adb
            **/*.e
            **/*.go
            **/*.lisp
            **/*.pp
            **/*.rs
            **/*.xsl
